version: '3.10'
services:
  mongo:
    image: mongo:4.2.5
  server:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
#services:
#  mongo:
#    image: mongo:4.2.5
#  app:
#    build: .
#    environment:
#      WAIT_HOSTS: mongo:27017
#    ports:
#      - '8080:8080'